AWSTemplateFormatVersion: 2010-09-09
Description: >-
  aws-sam-lambda-rest-api-typescript-example

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  helloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/functions/hello.getAllItemsHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  HelloWorldFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt helloFunction.Arn
  HelloWorldFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt helloFunctionRole.Arn
